package app

import (
	"context"
	"crypto/tls"
	_ "embed"
	"errors"
	"fmt"
	"log/slog"
	"net"
	"net/http"
	"os"
	"time"
)

const (
	defaultReadTimeout  = 10 * time.Second
	defaultWriteTimeout = 15 * time.Second
	defaultIdleTimeout  = 120 * time.Second
)

// The embedded development certificate is generated by `make ensure_dev_certs` into
// app/certs/ (gitignored) before every build. It is only used with env: dev, see loadTLSCert.

//go:embed certs/dev_cert.pem
var embeddedCertFile []byte

//go:embed certs/dev_key.pem
var embeddedKeyFile []byte

// StartWebServer initializes and starts the HTTPS server asynchronously.
// - Uses the file-based cert/key from config
// - Development fallback (env: dev only): embedded self-signed cert
// - Non-blocking: runs in goroutine
// - Graceful shutdown on app.ctx cancellation
// - A server that stops on its own is reported on app.serverErr, which restarts the App
func (app *App) StartWebServer() error {
	// Set default timeouts
	app.web.ReadTimeout = defaultReadTimeout
	app.web.WriteTimeout = defaultWriteTimeout
	app.web.IdleTimeout = defaultIdleTimeout

	// Load TLS certificate
	cert, err := loadTLSCert(app.config.Webserver.CertFile, app.config.Webserver.KeyFile, app.config.Env)
	if err != nil {
		return fmt.Errorf("failed to load TLS certificate: %w", err)
	}

	// Assign TLS config
	app.web.TLSConfig = &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   tls.VersionTLS12}

	// Create listener
	listener, err := net.Listen("tcp", app.web.Addr)
	if err != nil {
		return fmt.Errorf("failed to create listener: %w", err)
	}

	// Channel to report server runtime errors
	serverErrCh := make(chan error, 1)

	go func() {
		// ServeTLS blocks until Shutdown is called
		err := app.web.ServeTLS(listener, "", "")
		if err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErrCh <- err
		}

		// Close the listener when ServeTLS exits, but ignore the normal
		// already-closed case during graceful shutdown.
		if err := listener.Close(); err != nil && !errors.Is(err, net.ErrClosed) {
			slog.Error("Failed to close listener", "error", err)
		}
	}()

	// Goroutine to monitor runtime errors and handle shutdown
	app.wg.Go(func() {

		select {
		case err := <-serverErrCh:
			// The signal handler restarts the App. It must not be done from here: the
			// restart waits for this goroutine via app.wg.
			app.serverErr <- err
		case <-app.ctx.Done():
			ctxShutdown, cancel := context.WithTimeout(context.Background(), 5*time.Second)
			defer cancel()
			if err := app.web.Shutdown(ctxShutdown); err != nil {
				slog.Error("Failed to shutdown webserver gracefully", "error", err)
			} else {
				slog.Info("Webserver stopped gracefully")
			}
		}
	})

	return nil
}

// loadTLSCert loads the file-based cert. If certFile is missing it falls back to the embedded
// development cert, but only with env: dev - that cert's private key ships in every release
// binary, so with env: prod a missing certFile is an error instead.
func loadTLSCert(certFile, keyFile, env string) (tls.Certificate, error) {
	if _, err := os.Stat(certFile); err == nil {
		// Production cert
		return tls.LoadX509KeyPair(certFile, keyFile)
	} else if errors.Is(err, os.ErrNotExist) {
		if env == ProdEnv {
			return tls.Certificate{}, fmt.Errorf("certFile %s not found; the embedded development certificate is not used with env: %s", certFile, ProdEnv)
		}
		// Dev fallback
		slog.Warn("TLS cert file not found, using embedded fallback", "certFile", certFile, "env", env)
		return tls.X509KeyPair(embeddedCertFile, embeddedKeyFile)
	} else {
		return tls.Certificate{}, fmt.Errorf("failed to read cert file: %w", err)
	}
}
