// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves memory usage, goroutine count, version, hostname, Go runtime version, OS, and per meter the unit IDs, the time and age of the last valid snapshot, the last error and the snapshots discarded as implausible.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns 200 while every meter serves current values, 503 while a meter has delivered no valid snapshot for three poll intervals. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "Application is ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Values of a meter are outdated",
                        "schema": {
                            "$ref": "#/definitions/web.ApiError"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current application name and version. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "appVersion": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.Model": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "Application name (MODULE)",
                    "type": "string"
                },
                "appVersion": {
                    "description": "Current version of the application",
                    "type": "string"
                },
                "goVersion": {
                    "description": "Go runtime version",
                    "type": "string"
                },
                "heapAllocBytes": {
                    "description": "Allocated heap memory in bytes",
                    "type": "integer"
                },
                "hostname": {
                    "description": "Machine name where the app runs",
                    "type": "string"
                },
                "meters": {
                    "description": "Meters holds the diagnostic state per meter name: unit IDs, the last valid snapshot,\nthe last error and the snapshots discarded as implausible. Filled in by the caller.",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/meters.MeterStatus"
                    }
                },
                "numGoroutines": {
                    "description": "Current number of active goroutines",
                    "type": "integer"
                },
                "os": {
                    "description": "Operating system name",
                    "type": "string"
                },
                "sysMemoryBytes": {
                    "description": "Total memory obtained from the OS",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "UTC timestamp when health info was collected (RFC3339)",
                    "type": "string"
                },
                "uptimeSeconds": {
                    "description": "Application uptime in seconds",
                    "type": "number"
                }
            }
        },
        "meters.MeterStatus": {
            "type": "object",
            "properties": {
                "ageSeconds": {
                    "description": "Age of the served values",
                    "type": "number"
                },
                "discardedSnapshots": {
                    "description": "Snapshots discarded as implausible",
                    "type": "integer"
                },
                "lastError": {
                    "description": "Last failed or discarded poll",
                    "type": "string"
                },
                "lastErrorTime": {
                    "description": "Time of LastError",
                    "type": "string"
                },
                "lastSuccess": {
                    "description": "Last valid snapshot from the source",
                    "type": "string"
                },
                "ready": {
                    "description": "Values are current, see staleAfter",
                    "type": "boolean"
                },
                "unitIDs": {
                    "description": "Unit IDs the meter answers on",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "web.ApiError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
